/** OpenClaw managed and cron session-key utilities. */

import {
  buildCoworkExecutionSessionKey,
  buildCoworkSessionKey,
  DEFAULT_COWORK_AGENT_ID,
  parseCoworkSessionKey,
} from '../../../shared/cowork/sessionSegment';

export const DEFAULT_MANAGED_AGENT_ID = DEFAULT_COWORK_AGENT_ID;
export { buildCoworkExecutionSessionKey };

export interface ManagedSessionKey {
  agentId: string | null;
  sessionId: string;
}

export function buildManagedSessionKey(
  sessionId: string,
  agentId = DEFAULT_MANAGED_AGENT_ID,
): string {
  return buildCoworkSessionKey(sessionId, agentId);
}

export function parseManagedSessionKey(
  sessionKey: string | undefined | null,
): ManagedSessionKey | null {
  const parsed = parseCoworkSessionKey(sessionKey);
  return parsed ? { agentId: parsed.agentId, sessionId: parsed.sessionId } : null;
}

export function isManagedSessionKey(sessionKey: string | undefined | null): boolean {
  return parseManagedSessionKey(sessionKey) !== null;
}

/** Match cron-isolated session keys generated by the OpenClaw gateway. */
const CRON_SESSION_KEY_RE = /^(?:agent:[^:]+:)?cron:[0-9a-f-]+$/i;

export function isCronSessionKey(sessionKey: string): boolean {
  return CRON_SESSION_KEY_RE.test(sessionKey);
}
